import variables from '../../core/styles/shared/_variables.scss';
import {createGradient} from '../../core/utilities';
import {NEUTRAL_SINGLE_GRADIENT} from '../../core/constants';

import type {Theme} from './types';

export {
  BASE_ANIMATION_DURATION,
  XMLNS,
  LOAD_ANIMATION_DURATION,
  BAR_ANIMATION_HEIGHT_BUFFER,
  DEFAULT_BORDER_RADIUS,
  MIN_WIDTH_BORDER_RADIUS,
  FONT_SIZE_PADDING,
  HORIZONTAL_BAR_LABEL_HEIGHT,
  HORIZONTAL_BAR_LABEL_OFFSET,
  HORIZONTAL_GROUP_LABEL_HEIGHT,
  HORIZONTAL_SPACE_BETWEEN_SETS,
  HORIZONTAL_SPACE_BETWEEN_SINGLE,
  HORIZONTAL_SPACE_BETWEEN_CHART_AND_AXIS,
  MAX_X_AXIS_LINES,
  LINE_ANIMATION_FAST_DURATION,
  LINE_ANIMATION_SLOW_DURATION,
  LINE_ANIMATION_FAST_COUNT,
  LINE_ANIMATION_DURATION_STEP,
  TICK_SIZE,
  FONT_SIZE,
  BELOW_X_AXIS_MARGIN,
  SMALL_SCREEN,
  SMALL_FONT_SIZE,
  DIAGONAL_ANGLE,
  MIN_HORIZONTAL_LABEL_SPACE,
  DEFAULT_LABEL_RATIO,
  MIN_HORIZONTAL_TICKS,
  LINE_HEIGHT,
  LABEL_ELLIPSIS_LENGTH,
  SMALL_LABEL_WIDTH,
  LABEL_SPACE_MINUS_FIRST_AND_LAST,
  DEFAULT_MAX_Y,
  ROUNDED_BAR_RADIUS,
  MIN_BAR_HEIGHT,
  EMPTY_STATE_CHART_MIN,
  EMPTY_STATE_CHART_MAX,
  SPACING_TIGHT,
  SPACING_EXTRA_TIGHT,
  SPACING,
  SPACING_BASE_TIGHT,
  BarChartMargin,
  LineChartMargin,
  BARS_TRANSITION_CONFIG,
  BARS_SORT_TRANSITION_CONFIG,
  LINES_LOAD_ANIMATION_CONFIG,
  MAX_TRAIL_DURATION,
  HORIZONTAL_BAR_GROUP_DELAY,
  MASK_HIGHLIGHT_COLOR,
  MASK_SUBDUE_COLOR,
  colorWhite,
  colorBlack,
  colorPurpleDark,
  colorTeal,
  NEUTRAL_SINGLE_GRADIENT,
} from '../../core/constants';

export const DEFAULT_THEME: Theme = {
  seriesColors: {
    comparison: variables.colorDarkComparison,
    single: NEUTRAL_SINGLE_GRADIENT,
    upToFour: [
      createGradient(variables.colorIndigo70, variables.colorIndigo90),
      createGradient(variables.colorBlue70, variables.colorBlue90),
      createGradient(variables.colorMagenta70, variables.colorMagenta90),
      createGradient(variables.colorTeal70, variables.colorTeal90),
    ],
    fromFiveToSeven: [
      createGradient(variables.colorTeal70, variables.colorTeal90),
      createGradient(variables.colorBlue70, variables.colorBlue90),
      createGradient(variables.colorIndigo70, variables.colorIndigo90),
      createGradient(variables.colorPurple50, variables.colorPurple70),
      createGradient(variables.colorMagenta70, variables.colorMagenta90),
      createGradient(variables.colorOrange60, variables.colorOrange80),
      createGradient(variables.colorYellow20, variables.colorYellow40),
    ],
    all: [
      variables.colorTeal90,
      variables.colorBlue50,
      variables.colorIndigo90,
      variables.colorPurple70,
      variables.colorMagenta90,
      variables.colorOrange50,
      variables.colorYellow70,
      variables.colorTeal40,
      variables.colorBlue80,
      variables.colorIndigo40,
      variables.colorPurple90,
      variables.colorMagenta70,
      variables.colorOrange80,
      variables.colorYellow20,
    ],
  },
  tooltip: {
    backgroundColor: variables.colorGray150,
    valueColor: variables.colorGray00,
    labelColor: variables.colorGray30,
  },
  chartContainer: {
    borderRadius: '0px',
    padding: '0px',
    backgroundColor: variables.colorGray160,
  },
  line: {
    sparkArea: [
      {offset: 0, color: 'rgba(92, 105, 208, 0)'},
      {offset: 100, color: 'rgba(92, 105, 208, 0.15)'},
    ],
    hasSpline: true,
    style: 'solid',
    hasPoint: true,
    width: 2,
    pointStroke: variables.colorGray160,
  },
  bar: {
    hasRoundedCorners: true,
    innerMargin: 'Medium',
    outerMargin: 'Medium',
    zeroAsMinHeight: false,
  },
  grid: {
    showVerticalLines: false,
    showHorizontalLines: true,
    color: variables.colorGray140,
    horizontalOverflow: false,
    horizontalMargin: 0,
  },
  xAxis: {
    showTicks: false,
    labelColor: variables.colorGray30,
    hide: false,
  },
  yAxis: {
    backgroundColor: variables.colorGray160,
    labelColor: variables.colorGray30,
  },
  crossHair: {
    color: variables.colorGray70,
    width: 1,
  },
  legend: {
    labelColor: variables.colorGray30,
    valueColor: variables.colorGray00,
    trendIndicator: {
      positive: '#039c86',
      negative: '#f24f62',
      neutral: '#8C9196',
    },
  },
};

export const LIGHT_THEME: Theme = {
  seriesColors: {
    comparison: variables.colorLightComparison,
    single: NEUTRAL_SINGLE_GRADIENT,
    upToFour: [
      createGradient(variables.colorIndigo70, variables.colorIndigo90),
      createGradient(variables.colorBlue70, variables.colorBlue90),
      createGradient(variables.colorMagenta70, variables.colorMagenta90),
      createGradient(variables.colorTeal70, variables.colorTeal90),
    ],
    fromFiveToSeven: [
      createGradient(variables.colorTeal70, variables.colorTeal90),
      createGradient(variables.colorBlue70, variables.colorBlue90),
      createGradient(variables.colorIndigo70, variables.colorIndigo90),
      createGradient(variables.colorPurple70, variables.colorPurple90),
      createGradient(variables.colorMagenta70, variables.colorMagenta90),
      createGradient(variables.colorOrange70, variables.colorOrange90),
      createGradient(variables.colorYellow70, variables.colorYellow90),
    ],
    all: [
      variables.colorTeal90,
      variables.colorBlue70,
      variables.colorIndigo90,
      variables.colorPurple70,
      variables.colorMagenta90,
      variables.colorOrange80,
      variables.colorYellow50,
      variables.colorTeal70,
      variables.colorBlue80,
      variables.colorIndigo70,
      variables.colorPurple90,
      variables.colorMagenta70,
      variables.colorOrange110,
      variables.colorYellow70,
    ],
  },
  tooltip: {
    backgroundColor: variables.colorGray00,
    valueColor: variables.colorGray160,
    labelColor: variables.colorGray100,
  },
  chartContainer: {
    borderRadius: '0px',
    padding: '0px',
    backgroundColor: variables.colorGray00,
  },
  line: {
    sparkArea: [
      {offset: 0, color: 'rgba(92, 105, 208, 0)'},
      {offset: 100, color: 'rgba(92, 105, 208, 0.15)'},
    ],
    hasSpline: true,
    style: 'solid',
    hasPoint: true,
    width: 2,
    pointStroke: variables.colorGray00,
  },
  bar: {
    hasRoundedCorners: true,
    innerMargin: 'Medium',
    outerMargin: 'Medium',
    zeroAsMinHeight: false,
  },
  grid: {
    showVerticalLines: false,
    showHorizontalLines: true,
    color: variables.colorGray20,
    horizontalOverflow: false,
    horizontalMargin: 0,
  },
  xAxis: {
    showTicks: false,
    labelColor: variables.colorGray100,
    hide: false,
  },
  yAxis: {
    backgroundColor: variables.colorGray00,
    labelColor: variables.colorGray100,
  },
  crossHair: {
    color: variables.colorGray40,
    width: 1,
  },
  legend: {
    valueColor: variables.colorGray160,
    labelColor: variables.colorGray100,
    trendIndicator: {
      positive: '#119d7f',
      negative: '#eb4c5e',
      neutral: '#8C9196',
    },
  },
};

export const PRINT_THEME = {
  ...LIGHT_THEME,
  seriesColors: {
    comparison: variables.colorLightComparison,
    single: variables.colorIndigo90,
    upToFour: [
      variables.colorIndigo70,
      variables.colorBlue70,
      variables.colorMagenta70,
      variables.colorTeal70,
    ],
    fromFiveToSeven: [
      variables.colorTeal70,
      variables.colorBlue70,
      variables.colorIndigo70,
      variables.colorPurple70,
      variables.colorMagenta70,
      variables.colorOrange70,
      variables.colorYellow70,
    ],
    all: [
      variables.colorTeal90,
      variables.colorBlue70,
      variables.colorIndigo90,
      variables.colorPurple70,
      variables.colorMagenta90,
      variables.colorOrange80,
      variables.colorYellow50,
      variables.colorTeal70,
      variables.colorBlue80,
      variables.colorIndigo70,
      variables.colorPurple90,
      variables.colorMagenta70,
      variables.colorOrange110,
      variables.colorYellow70,
    ],
  },
};
