name: polaris-viz
up:
  - node:
      yarn: 1.22.5
      version: v16.12.0 # to be kept in sync with .nvmrc .github/workflows/main.yml

open:
  app: http://localhost:8080/
  shipit: https://shipit.shopify.io/shopify/polaris-viz/production
  coverage: build/coverage/index.html

commands:
  # People new to the project might be tempted to run some
  # common commands, so let’s have them in here.
  # For a list of Common Commands in Projects, check out:
  # https://development.shopify.io/engineering/keytech/dev/getting_started/Common-Commands-in-Projects
  build: yarn run build
  server: yarn run dev
  style: yarn run lint
  test: yarn run test
  test:coverage: yarn run test:coverage
  type-check: yarn run type-check
  storybook: yarn storybook
  add-story: yarn add:story
