export const MIN_BAR_HEIGHT = 5;
export const MARGIN = {Top: 5, Right: 20, Bottom: 25, Left: 0};
export const LINE_HEIGHT = 12;
export const TICK_SIZE = 6;
export const MIN_Y_LABEL_SPACE = 80;
export const SPACING = 8;
export const SMALL_SCREEN = 500;
export const FONT_SIZE = 12;
export const SMALL_FONT_SIZE = 10;
