name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  # pull_request:
  #   types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to General Backlog
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/Shopify/polaris-viz/projects/1'
        column_name: 'Backlog ( Unprioritized )'
