name: Size Limit

on:
  pull_request:
    branches:
      - '**'
jobs:
  size:
    name: Size Limit
    runs-on: self-hosted
    env:
      CI_JOB_NUMBER: 1
    steps:
      # Needed as self-hosted runners don't come with yarn
      - name: Install Yarn
        run: npm install -g yarn
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
