name: Size Limit

on:
  pull_request:
    branches:
      - '**'
jobs:
  size:
    name: Size Limit
    runs-on: ubuntu-latest
    container: node:16.19.1
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
