import type {Story} from '@storybook/react';

import type {GridProps, CellGroup} from '../Grid';
import {Grid} from '../Grid';

export const Template: Story<GridProps> = (args: GridProps) => {
  return <Grid {...args} />;
};

export const CELL_GROUPS: CellGroup[] = [
  {
    start: {row: 0, col: 0},
    end: {row: 0, col: 1},
    secondaryValue: '(10%)',
    value: '8,000',
    bgColor: '#B1C3F7',
    color: '#000000',
    name: 'Previously loyal',
    connectedGroups: ['Loyal'],
    description:
      'Customers without recent purchases, but with a very strong history of orders and spend.',
    goal: 'Goal: move customers to Loyal',
  },
  {
    start: {row: 1, col: 0},
    end: {row: 2, col: 1},
    secondaryValue: '(20%)',
    value: '200',
    bgColor: '#CBD7F9',
    color: '#000000',
    name: 'At risk',
    connectedGroups: ['Needs attention', 'Loyal'],
    description:
      'Customers without recent purchases, but with a strong history of orders and spend.',
    goal: 'Goal: move customers to Loyal or Needs Attention',
  },
  {
    start: {row: 3, col: 0},
    end: {row: 4, col: 1},
    secondaryValue: '(30%)',
    value: '2,000',
    bgColor: '#E5EBFC',
    color: '#000000',
    name: 'Dormant',
    connectedGroups: ['Almost lost'],
    description:
      'Customers without recent orders, with infrequent orders, and with low spend.',
    goal: 'Goal: move customers to Almost lost',
  },
  {
    start: {row: 0, col: 2},
    end: {row: 1, col: 3},
    secondaryValue: '(40%)',
    value: '80',
    bgColor: '#0B2062',
    color: '#FFFFFF',
    name: 'Loyal',
    connectedGroups: ['Champions'],
    description:
      'Customers without recent purchases, but with a very strong history of orders and spend.',
    goal: 'Goal: move customers to Loyal',
  },
  {
    start: {row: 2, col: 2},
    end: {row: 2, col: 2},
    secondaryValue: '(20%)',
    value: '500',
    bgColor: '#3E69EA',
    color: '#FFFFFF',
    name: 'Needs attention',
    connectedGroups: ['Loyal', 'Active'],
    description:
      'Customers who buy less recently, order sometimes and spend moderately with your store.',
    goal: 'Goal: move customers to Loyal or Potential',
  },
  {
    start: {row: 3, col: 2},
    end: {row: 4, col: 2},
    secondaryValue: '(10%)',
    value: '8,000',
    bgColor: '#7594F0',
    color: '#000000',
    name: 'Almost lost',
    connectedGroups: ['Active', 'Promising'],
    description:
      'Customers without recent purchases, fewer orders, and with lower spend.',
    goal: 'Goal: move customers to Active or Promising',
  },
  {
    start: {row: 4, col: 3},
    end: {row: 4, col: 3},
    secondaryValue: '(20%)',
    value: '200',
    bgColor: '#194BE3',
    color: '#FFFFFF',
    name: 'Promising',
    connectedGroups: ['Active'],
    description: 'Customers with recent purchases, few orders, and low spend.',
    goal: 'Goal: move customers to Active.',
  },
  {
    start: {row: 2, col: 3},
    end: {row: 3, col: 4},
    secondaryValue: '(30%)',
    value: '2,000',
    bgColor: '#0D297C',
    color: '#FFFFFF',
    name: 'Active',
    connectedGroups: ['Loyal', 'Champions'],
    description:
      'Customers with recent purchases, some orders, and moderate spend.',
    goal: 'Goal: move customers to Champions or Loyal',
  },
  {
    start: {row: 4, col: 4},
    end: {row: 4, col: 4},
    secondaryValue: '(40%)',
    value: '80',
    bgColor: '#133AAF',
    color: '#FFFFFF',
    name: 'New',
    connectedGroups: ['Active'],
    description:
      'Customers with very recent purchases, few orders, and low spend.',
    goal: 'Goal: move customers to Active',
  },
  {
    start: {row: 0, col: 4},
    end: {row: 1, col: 4},
    secondaryValue: '(20%)',
    value: '500',
    bgColor: '#081848',
    color: '#FFFFFF',
    name: 'Champions',
    description:
      'Customers with very recent purchases, many orders, and the most spend.',
    goal: null,
  },
];

export const RANDOM_CELL_GROUPS: CellGroup[] = [
  {
    start: {row: 0, col: 0},
    end: {row: 0, col: 1},
    bgColor: '#4c1d95',
    color: '#FFFFFF',
    name: 'Revenue',
    value: '$12,345',
    secondaryValue: '+15%',
    description: 'Total revenue for the period',
    goal: 'Increase by 20%',
    connectedGroups: ['Orders'],
  },
  {
    start: {row: 1, col: 0},
    end: {row: 1, col: 1},
    bgColor: '#6d28d9',
    color: '#FFFFFF',
    name: 'Orders',
    value: '1,234',
    secondaryValue: '↑ 8%',
    description: 'Total number of orders',
    goal: 'Maintain growth rate',
    connectedGroups: ['Revenue'],
  },
  {
    start: {row: 2, col: 0},
    end: {row: 2, col: 1},
    bgColor: '#8b5cf6',
    color: '#000000',
    name: 'Conversion',
    value: '2.4%',
    secondaryValue: '↓ 0.5%',
    description: 'Conversion rate from visits to orders',
    goal: 'Increase to 3%',
    connectedGroups: ['Orders'],
  },
  {
    start: {row: 0, col: 2},
    end: {row: 0, col: 3},
    bgColor: '#701a75',
    color: '#FFFFFF',
    name: 'Average Order',
    value: '$98.50',
    secondaryValue: '+$12.30',
    description: 'Average order value',
    goal: 'Increase to $100',
    connectedGroups: ['Return Rate'],
  },
  {
    start: {row: 1, col: 2},
    end: {row: 2, col: 3},
    bgColor: '#a21caf',
    color: '#FFFFFF',
    name: 'Customer Satisfaction',
    value: '4.8★',
    secondaryValue: '+0.2',
    description: 'Average customer satisfaction rating',
    goal: 'Maintain above 4.5',
    connectedGroups: ['Return Rate'],
  },
  {
    start: {row: 0, col: 4},
    end: {row: 2, col: 4},
    bgColor: '#d946ef',
    color: '#000000',
    name: 'Return Rate',
    value: '3.2%',
    secondaryValue: '-0.8%',
    description: 'Product return rate',
    goal: 'Keep below 5%',
    connectedGroups: [],
  },
  {
    start: {row: 3, col: 0},
    end: {row: 3, col: 1},
    bgColor: '#c4b5fd',
    color: '#000000',
    name: 'New Users',
    value: '5,678',
    secondaryValue: '+25%',
    description: 'New user registrations',
    goal: 'Increase by 30%',
    connectedGroups: ['Conversion'],
  },
  {
    start: {row: 4, col: 0},
    end: {row: 4, col: 1},
    bgColor: '#831843',
    color: '#FFFFFF',
    name: 'Session Duration',
    value: '12:45',
    secondaryValue: '+2:30',
    description: 'Average time spent on site',
    goal: 'Increase to 15 minutes',
    connectedGroups: ['Conversion'],
  },
  {
    start: {row: 3, col: 2},
    end: {row: 3, col: 3},
    bgColor: '#be185d',
    color: '#FFFFFF',
    name: 'Cart Abandonment',
    value: '23%',
    secondaryValue: '↓ 2%',
    description: 'Rate of abandoned shopping carts',
    goal: 'Reduce to 20%',
    connectedGroups: ['Page Load Time'],
  },
  {
    start: {row: 4, col: 2},
    end: {row: 4, col: 3},
    bgColor: '#ec4899',
    color: '#000000',
    name: 'Mobile Users',
    value: '68%',
    secondaryValue: '+5%',
    description: 'Percentage of mobile visitors',
    goal: 'Maintain above 65%',
    connectedGroups: ['Page Load Time'],
  },
  {
    start: {row: 3, col: 4},
    end: {row: 4, col: 4},
    bgColor: '#f9a8d4',
    color: '#000000',
    name: 'Page Load Time',
    value: '1.2s',
    secondaryValue: '-0.3s',
    description: 'Average page load time',
    goal: 'Keep under 1.5s',
    connectedGroups: ['Return Rate'],
  },
];
