import type {Story} from '@storybook/react';

import type {GridProps} from '../Grid';
import {Grid} from '../Grid';

export const Template: Story<GridProps> = (args: GridProps) => {
  return <Grid {...args} />;
};

export const CELL_GROUPS = [
  {
    start: {row: 0, col: 0},
    end: {row: 0, col: 1},
    secondaryValue: '(10%)',
    value: '8,000',
    bgColor: '#B1C3F7',
    color: '#000000',
    name: 'Previously loyal',
    connectedGroups: ['Loyal'],
    description:
      'Customers without recent purchases, but with a very strong history of orders and spend',
    goal: 'Goal: move customers to Loyal',
  },
  {
    start: {row: 1, col: 0},
    end: {row: 2, col: 1},
    secondaryValue: '(20%)',
    value: '200',
    bgColor: '#CBD7F9',
    color: '#000000',
    name: 'At risk',
    connectedGroups: ['Needs attention', 'Loyal'],
    description:
      'Customers without recent purchases, but with a strong history of orders and spend.',
    goal: 'Goal: move customers to Loyal or Needs Attention',
  },
  {
    start: {row: 3, col: 0},
    end: {row: 4, col: 1},
    secondaryValue: '(30%)',
    value: '2,000',
    bgColor: '#E5EBFC',
    color: '#000000',
    name: 'Dormant',
    connectedGroups: ['Almost lost'],
    description:
      'Customers without recent orders, with infrequent orders, and with low spend.',
    goal: 'Goal: move customers to Almost lost.',
  },
  {
    start: {row: 0, col: 2},
    end: {row: 1, col: 3},
    secondaryValue: '(40%)',
    value: '80',
    bgColor: '#0B2062',
    color: '#FFFFFF',
    name: 'Loyal',
    connectedGroups: ['Champions'],
    description:
      'Customers without recent purchases, but with a very strong history of orders and spend.',
    goal: 'Goal: move customers to Loyal.',
  },
  {
    start: {row: 2, col: 2},
    end: {row: 2, col: 2},
    secondaryValue: '(20%)',
    value: '500',
    bgColor: '#3E69EA',
    color: '#FFFFFF',
    name: 'Needs attention',
    connectedGroups: ['Loyal', 'Active'],
    description:
      'Customers who buy less recently, order sometimes and spend moderately with your store.',
    goal: 'Goal: move customers to Loyal or Potential.',
  },
  {
    start: {row: 3, col: 2},
    end: {row: 4, col: 2},
    secondaryValue: '(10%)',
    value: '8,000',
    bgColor: '#7594F0',
    color: '#000000',
    name: 'Almost lost',
    connectedGroups: ['Active', 'Promising'],
    description:
      'Customers without recent purchases, fewer orders, and with lower spend.',
    goal: 'Goal: move customers to Active or Promising.',
  },
  {
    start: {row: 4, col: 3},
    end: {row: 4, col: 3},
    secondaryValue: '(20%)',
    value: '200',
    bgColor: '#194BE3',
    color: '#FFFFFF',
    name: 'Promising',
    connectedGroups: ['Active'],
    description: 'Customers with recent purchases, few orders, and low spend.',
    goal: 'Goal: move customers to Active.',
  },
  {
    start: {row: 2, col: 3},
    end: {row: 3, col: 4},
    secondaryValue: '(30%)',
    value: '2,000',
    bgColor: '#0D297C',
    color: '#FFFFFF',
    name: 'Active',
    connectedGroups: ['Loyal', 'Champions'],
    description:
      'Customers with recent purchases, some orders, and moderate spend.',
    goal: 'Goal: move customers to Champions or Loyal.',
  },
  {
    start: {row: 4, col: 4},
    end: {row: 4, col: 4},
    secondaryValue: '(40%)',
    value: '80',
    bgColor: '#133AAF',
    color: '#FFFFFF',
    name: 'New',
    connectedGroups: ['Active'],
    description:
      'Customers with very recent purchases, few orders, and low spend.',
    goal: 'Goal: move customers to Active.',
  },
  {
    start: {row: 0, col: 4},
    end: {row: 1, col: 4},
    secondaryValue: '(20%)',
    value: '500',
    bgColor: '#081848',
    color: '#FFFFFF',
    name: 'Champions',
    description:
      'Customers with very recent purchases, many orders, and the most spend.',
    goal: null,
  },
];

export const RANDOM_CELL_GROUPS = [
  {
    start: {row: 0, col: 0},
    end: {row: 1, col: 1},
    secondaryValue: '(15%)',
    value: '12,000',
    bgColor: '#f97316',
    color: '#000000',
    name: 'New Releases',
    connectedGroups: ['Trending'],
    description: 'Recently launched products with high potential',
    goal: 'Increase market penetration',
  },
  {
    start: {row: 0, col: 2},
    end: {row: 1, col: 3},
    secondaryValue: '(10%)',
    value: '8,000',
    bgColor: '#f59e0b',
    color: '#000000',
    name: 'Emerging Bestsellers',
    connectedGroups: [],
    description: 'Products showing early signs of popularity',
    goal: 'Boost sales and visibility',
  },
  {
    start: {row: 0, col: 4},
    end: {row: 1, col: 5},
    secondaryValue: '(8%)',
    value: '6,500',
    bgColor: '#22c55e',
    color: '#000000',
    name: 'Trending Items',
    connectedGroups: [],
    description: 'Rapidly gaining popularity in the market',
    goal: 'Capitalize on current trends',
  },
  {
    start: {row: 0, col: 6},
    end: {row: 1, col: 7},
    secondaryValue: '(5%)',
    value: '4,000',
    bgColor: '#10b981',
    color: '#000000',
    name: 'Limited Editions',
    connectedGroups: ['Flagship Products'],
    description: 'Exclusive products with high demand',
    goal: 'Create scarcity and boost brand value',
  },
  {
    start: {row: 2, col: 0},
    end: {row: 3, col: 1},
    secondaryValue: '(25%)',
    value: '20,000',
    bgColor: '#06b6d4',
    color: '#000000',
    name: 'Staple Products',
    connectedGroups: ['Seasonal Items', 'New Releases'],
    description: 'Consistent sellers with steady demand',
    goal: 'Maintain market share and improve margins',
  },
  {
    start: {row: 2, col: 2},
    end: {row: 3, col: 3},
    secondaryValue: '(12%)',
    value: '9,600',
    bgColor: '#3b82f6',
    color: '#000000',
    name: 'Seasonal Items',
    connectedGroups: ['Premium Line'],
    description: 'Products with peak demand during specific seasons',
    goal: 'Optimize inventory and extend selling period',
  },
  {
    start: {row: 2, col: 4},
    end: {row: 3, col: 5},
    secondaryValue: '(7%)',
    value: '5,600',
    bgColor: '#6366f1',
    color: '#000000',
    name: 'Premium Line',
    connectedGroups: ['Trending Items', 'Flagship Products'],
    description: 'High-end products with superior margins',
    goal: 'Enhance brand prestige and increase market share',
  },
  {
    start: {row: 2, col: 6},
    end: {row: 3, col: 7},
    secondaryValue: '(3%)',
    value: '2,400',
    bgColor: '#8b5cf6',
    color: '#000000',
    name: 'Flagship Products',
    connectedGroups: ['Limited Editions'],
    description: 'Signature items representing the brand',
    goal: 'Maintain product excellence and brand loyalty',
  },
  {
    start: {row: 4, col: 0},
    end: {row: 5, col: 1},
    secondaryValue: '(6%)',
    value: '4,800',
    bgColor: '#a855f7',
    color: '#000000',
    name: 'Declining Products',
    connectedGroups: ['Seasonal Items', 'Discontinued Items'],
    description: 'Products showing decreased sales',
    goal: 'Revitalize or phase out strategically',
  },
  {
    start: {row: 4, col: 2},
    end: {row: 5, col: 3},
    secondaryValue: '(2%)',
    value: '1,600',
    bgColor: '#ec4899',
    color: '#000000',
    name: 'Discontinued Items',
    connectedGroups: ['Declining Products', 'Clearance Items'],
    description: 'Products being phased out of the catalog',
    goal: 'Maximize remaining inventory value',
  },
  {
    start: {row: 4, col: 4},
    end: {row: 5, col: 5},
    secondaryValue: '(1%)',
    value: '800',
    bgColor: '#f43f5e',
    color: '#000000',
    name: 'Clearance Items',
    connectedGroups: ['Premium Line', 'Bestsellers'],
    description: 'Products on sale to clear inventory',
    goal: 'Quickly convert inventory to cash',
  },
  {
    start: {row: 4, col: 6},
    end: {row: 5, col: 7},
    secondaryValue: '(0.5%)',
    value: '400',
    bgColor: '#8A2BE2',
    color: '#000000',
    name: 'Bestsellers',
    connectedGroups: ['Flagship Products'],
    description: 'Top-selling products across categories',
    goal: 'Maintain popularity and expand product line',
  },
  {
    start: {row: 6, col: 0},
    end: {row: 7, col: 1},
    secondaryValue: '(2.5%)',
    value: '2,000',
    bgColor: '#20B2AA',
    color: '#000000',
    name: 'Rising Stars',
    connectedGroups: [],
    description: 'Products showing potential for high sales',
    goal: 'Accelerate growth and increase visibility',
  },
  {
    start: {row: 6, col: 2},
    end: {row: 7, col: 3},
    secondaryValue: '(1.5%)',
    value: '1,200',
    bgColor: '#00CED1',
    color: '#000000',
    name: 'Influencer Favorites',
    connectedGroups: ['Discontinued Items'],
    description: 'Products popular among social media influencers',
    goal: 'Leverage for brand promotion and increased sales',
  },
  {
    start: {row: 6, col: 4},
    end: {row: 7, col: 5},
    secondaryValue: '(1%)',
    value: '800',
    bgColor: '#5F9EA0',
    color: '#000000',
    name: 'Beta Products',
    connectedGroups: ['Customer Feedback Items'],
    description: 'Products in testing phase before full launch',
    goal: 'Gather feedback and refine product features',
  },
  {
    start: {row: 6, col: 6},
    end: {row: 7, col: 7},
    secondaryValue: '(0.5%)',
    value: '400',
    bgColor: '#48D1CC',
    color: '#000000',
    name: 'Customer Feedback Items',
    connectedGroups: ['Beta Products'],
    description: 'Products developed based on customer suggestions',
    goal: 'Improve customer satisfaction and loyalty',
  },
];
